name: Tests

on:
  [push]

env:
  CARGO_TERM_COLOR: always
  TERM: xterm-256color

jobs:

  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update --no-self-update
          rustup default

      - name: Install wasi2ic and wasm32-wasip1
        run: |
          rustup target add wasm32-wasip1
          cargo install wasi2ic
          cargo install ic-wasm
          cargo install ic-test

      - name: Build
        run: |
          cargo build -p backend --target wasm32-wasip1 --release
          wasi2ic target/wasm32-wasip1/release/backend.wasm target/wasm32-wasip1/release/nowasi.wasm
          echo "Build successful!"

      - name: Run tests
        run: |
          cargo test -p tests
          echo "Tests successful!"
